"""Adiciona controlo de aulas contratadas ao Aluno

Revision ID: 09076edc2bb9
Revises: 7c158bffb43b
Create Date: 2025-08-27 09:11:34.557167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09076edc2bb9'
down_revision = '7c158bffb43b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aulas_praticas_contratadas', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('aulas_simulador_contratadas', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('aulas_extras_contratadas', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.drop_column('aulas_extras_contratadas')
        batch_op.drop_column('aulas_simulador_contratadas')
        batch_op.drop_column('aulas_praticas_contratadas')

    op.drop_table('admin')
    # ### end Alembic commands ###
