"""Adiciona campo de categoria para Aluno

Revision ID: 6062f6790de3
Revises: 795ddb35cf83
Create Date: 2025-08-21 16:11:39.420184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6062f6790de3'
down_revision = '795ddb35cf83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.Enum('A', 'B', 'C', 'D', 'E', 'AB', name='categoriacnh', native_enum=False), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
