"""Adiciona status EM_ANDAMENTO para aulas

Revision ID: 795ddb35cf83
Revises: 7919ed92bc13
Create Date: 2025-08-20 16:09:24.667998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795ddb35cf83'
down_revision = '7919ed92bc13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aula', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('AGENDADA', 'CONCLUIDA', 'CANCELADA', 'EM_ANDAMENTO', name='aulastatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aula', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('AGENDADA', 'CONCLUIDA', 'CANCELADA', 'EM_ANDAMENTO', name='aulastatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    # ### end Alembic commands ###
