"""Criação inicial da base de dados com tipos de veículo

Revision ID: 7c158bffb43b
Revises: 
Create Date: 2025-08-21 17:42:36.534565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c158bffb43b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'INSTRUTOR', 'ALUNO', name='userrole', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=8), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('MOTOCICLETA', 'CARRO', 'ONIBUS', 'CAMINHAO', name='tipoveiculo', native_enum=False), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=True),
    sa.Column('categoria', sa.Enum('A', 'B', 'C', 'D', 'E', 'AB', name='categoriacnh', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('instrutor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnh', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnh')
    )
    op.create_table('aula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('AGENDADA', 'CONCLUIDA', 'CANCELADA', 'EM_ANDAMENTO', name='aulastatus', native_enum=False), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('instrutor_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['instrutor_id'], ['instrutor.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aula')
    op.drop_table('instrutor')
    op.drop_table('aluno')
    op.drop_table('veiculo')
    op.drop_table('usuario')
    # ### end Alembic commands ###
