"""Adiciona tipo de aula ao modelo Aula

Revision ID: e1b535d450e2
Revises: 09076edc2bb9
Create Date: 2025-08-27 15:17:01.065379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b535d450e2'
down_revision = '09076edc2bb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_aula', sa.Enum('PRATICA', 'SIMULADOR', 'EXTRA', name='tipoaula', native_enum=False), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aula', schema=None) as batch_op:
        batch_op.drop_column('tipo_aula')

    # ### end Alembic commands ###
